### ISSUE TITLE
存在丢包时，IMService.appendData()可能会导致byte[] data的大小无限增长

### ISSUE THREAD

**Issue by ImKarl** [GoBelieveIO/im_android#7]
因为丢包可能导致接受的消息不是预期的结果，所以解包可能一直是失败的。
由于上述原因，data始终不会被消费掉，最终会因此导致OOM。

希望能修复下这个问题……Thx

**Comment by richmonkey** [comment]
有运行时的log吗？

**Comment by richmonkey** [comment]
tcp 丢包是个什么概念？

**Comment by richmonkey** [comment]
diff --git a/imsdk/src/main/java/com/beetle/im/IMService.java b/imsdk/src/main/java/com/beetle/im/IMService.java
index 7483e54..a7a4901 100644
--- a/imsdk/src/main/java/com/beetle/im/IMService.java
+++ b/imsdk/src/main/java/com/beetle/im/IMService.java
@@ -1592,6 +1592,9 @@ public class IMService {
         byte[] left = new byte[this.data.length - pos];
         System.arraycopy(this.data, pos, left, 0, left.length);
         this.data = left;
+        if (this.data.length > Message.MAX_MESSAGE_SIZE) {
+            return false;
+        }
         return true;
     }

diff --git a/imsdk/src/main/java/com/beetle/im/Message.java b/imsdk/src/main/java/com/beetle/im/Message.java
index c428d47..ab61cbf 100644
--- a/imsdk/src/main/java/com/beetle/im/Message.java
+++ b/imsdk/src/main/java/com/beetle/im/Message.java
@@ -105,6 +105,7 @@ public class Message {

     private static final int VERSION = 2;

+    public static final int MAX_MESSAGE_SIZE = 64*1024;//最大消息长度
     public static final int HEAD_SIZE = 8;
     public int cmd;
     public int seq;

**Comment by richmonkey** [comment]
[size.txt](https://github.com/GoBelieveIO/im_android/files/4329452/size.txt)
麻烦测试下这个patch是不是能解决这个问题？
校验data的大小， 如果data超过64k（单个消息最大长度）， 则断开socket重新链接

**Comment by ImKarl** [comment]
复现方式：
- 客户端A 下线
- 给客户端发送大量超过 1K 大小的文本内容消息
- 客户端A 上线
- 客户端A 断网
- 客户端A 联网
- 重复断网、联网操作
- 一段时间后，会导致`byte[] data`变成不可解包的数据，大小持续增加(心跳)

以下是在 `IMService.handleData()` 中打印 `"handleData: "+this.data.length`的Log日志：

![image](https://user-images.githubusercontent.com/3197744/76719225-18503b80-6774-11ea-8108-883aa672ca00.png)

**Comment by richmonkey** [comment]
麻烦发下完整日志 文本附件

**Comment by ImKarl** [comment]
涉及到公司数据，不太方便发、  而且日志也没有看到其他额外的有用信息

**Comment by richmonkey** [comment]
过滤tag， 保留imservice的日志就好了

**Comment by richmonkey** [comment]
还有你们用的sdk 的版本（commit id）， 链接的服务器地址是？

**Comment by ImKarl** [comment]
我没有用你前面发的patch版本

客户端代码没有改动，服务器端代码不清楚有没有改动

**Comment by richmonkey** [comment]
1.提供客户端 imservice 完整日志
2.使用patch，测试问题是否解决， 如果没有解决，然后提供客户端 imservice的完整日志
3.同时请告知明确的版本（包括客户端及服务端），明确服务端代码的改动， 还请贵公司遵守服务器所使用的开源协议。

**Comment by ImKarl** [comment]
1. 完整日志我在尝试分离导出
2. 你前面给的patch方案，我不太认同，如果消息堆积太多，正常逻辑就存在超过64k的情况
3. 刚刚跟我司后端确认了，后端代码也是没有修改过的。另外，你们的开源协议是什么？在哪里声明了，我去看看

**Comment by richmonkey** [comment]
"3.同时请告知明确的版本（包括客户端及服务端)"
patch解决的根据是：堆积在data缓存的单条消息不会超过64k
保留在data一定是不完整的一条消息， 否则是不会堆积在data缓存中的。
不认可也麻烦测试下

**Comment by ImKarl** [comment]
[logcat_imservice.txt](https://github.com/GoBelieveIO/im_android/files/4335940/logcat_imservice.txt)

这个是基于18年3月份的Android端代码打印的日志；

服务器端是去年的代码，具体时间、commitId找不到。

**Comment by richmonkey** [comment]
你版本太旧了， 麻烦更新到最新的版本

**Comment by ImKarl** [comment]
对比过最新版的代码，逻辑还是一样的。而且我刚看了你的patch的修改内容，也不能解决data无限增长的问题。
把data清空倒是可以：
```
if (this.data.length > Message.MAX_MESSAGE_SIZE) {
    this.data = null;
    return false;
}
```

**Comment by richmonkey** [comment]
欢迎基于最新版本的pr，我们没有办法维护18年的版本了

**Comment by ImKarl** [comment]
你们最新版本同样存在这个问题。

**Comment by ImKarl** [comment]
归根结底，之所以会出现这个问题，还是因为没有考虑丢包问题。
如果在每个包之间增加特殊标志内容，以该标志分割每一个包，就不可能出现data无限增长的可能。

**Comment by richmonkey** [comment]
你怎么确定新版本有同样问题？还是请测试一下， 提供下完整日志

**Comment by ImKarl** [comment]
已经决定弃坑了～

**Comment by richmonkey** [comment]
如果你觉得自己的方案是对的， 我们欢迎pr

**Comment by richmonkey** [comment]
if (this.data.length > Message.MAX_MESSAGE_SIZE) {
    this.data = null;
    return false;
}
handleData  return false; 会导致socket 重新链接， socket重新连接是会清空this.data缓存的， 所以这里的this.data =null；是多余的。

**Comment by richmonkey** [comment]
18年的版本可能在重新链接socket的时候， 没有清空 this.data

**Comment by ImKarl** [comment]
确实如此，看最新的代码 `this.data` 会在连接上时清空，可以避免data无限增长。
但是在网络较差是，通过反复重连来解决丢包问题，实在是不可取。
